[package]
name = "number-guesser-bot"
version = "1.0.0"
authors = ["Piyush Bhangale <bhangalepiyush@gmail.com>"]
edition = "2018"


[dependencies]
rand = "0.3.14"
serenity = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"